Add built-in monitoring configs
aws-samples/amazon-ecs-firelens-examples pull request #88
Opened 2022-11-21 05:38 UTC by PettitWesley

Signed-off-by: Wesley Pettit <wppttt@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-21 05:38 UTC, PettitWesley commented on examples/fluent-bit/health-check/README.md
> +See the [task-definition-output-metrics-healthcheck.json](task-definition-output-metrics-healthcheck.json) in this directory. This health check uses the built-in `/fluent-bit/configs/output-metrics-h
Must wait till we merge and release: https://github.com/aws/aws-for-fluent-bit/pull/485

2022-11-21 05:39 UTC, PettitWesley commented on examples/fluent-bit/send-fb-internal-metrics-to-cw/README.md
> +For a quick setup, use the built-in plugin metrics configuration file available in AWS for Fluent Bit 2.X.Y+. This built-in configuration means that you do not have to build a custom Fluent Bit image
Must wait till we merge and release: https://github.com/aws/aws-for-fluent-bit/pull/485

2022-11-21 20:09 UTC, matthewfala requested changes
There's a broken link

2022-11-21 20:09 UTC, matthewfala commented on examples/fluent-bit/health-check/README.md
> +See the [task-definition-output-metrics-healthcheck.json](task-definition-output-metrics-healthcheck.json) in this directory. This health check uses the built-in `/fluent-bit/configs/output-metrics-h
This link doesn't work

2022-12-17 02:21 UTC, PettitWesley commented on examples/fluent-bit/health-check/README.md
> +See the [task-definition-output-metrics-healthcheck.json](task-definition-output-metrics-healthcheck.json) in this directory. This health check uses the built-in `/fluent-bit/configs/output-metrics-h
This is merged but not yet released. Should be part of 2.30.0

2023-01-18 22:01 UTC, PettitWesley commented on examples/fluent-bit/health-check/README.md
> +See the [task-definition-output-metrics-healthcheck.json](task-definition-output-metrics-healthcheck.json) in this directory. This health check uses the built-in `/fluent-bit/configs/output-metrics-h
We just released this in 2.29.1

2023-01-18 22:10 UTC, matthewfala approved these changes
This is great!

2023-01-18 22:13 UTC, Claych approved these changes

2023-01-18 22:23 UTC, merged